version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: etec-pi-2024-backend-drolito123-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shirtdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: shirtdb
    depends_on:
      - mysql

volumes:
  mysql_data:
