version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: etec-pi-2024-backend-drolito123-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shirtdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql_container
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: shirtdb
    depends_on:
      - mysql
    command: sh -c "sleep 10 && npx ts-node src/app.ts"  # Añade un retraso de 10 segundos

volumes:
  mysql_data:
