version: "3"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=DB
    depends_on:
      - db
    networks:
      - santos-app-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=DB
    ports:
      - "3307:3306"  # Puerto expuesto en tu máquina
    restart: always
    networks:
      - santos-app-network

networks:
  santos-app-network:
    external: true
